output:

linters-settings:
  errcheck:
    check-type-assertion: true
    check-blank: true
  funlen:
    lines: 100
    statements: 80
  gcognit:
    min-complexity: 20
  gocyclo:
    min-complexity: 20
  cyclop:
    max-complexity: 20
    package-average: 0.0
  nestif:
    min-complexity: 7
  goconst:
    min-len: 0
    min-occurences: 5
  gocritic:
  godot:
    comments: all
  lll:
    line-length: 120
  misspell:
    local: US
  predeclared:
    q: true
  unused:
    check-exported: false
  wsl:
    allow-cuddle-declarations: true

linters:
  enable-all: true
  disable: nlreturn,nolintlint,tparallel,testpackage,gci,scopelint,gochecknoglobals,interfacer,maligned,golint,dupl,gochecknoinits,goconst,gomnd
