.TH EC 1 "05 Oct 2020" "\[u00A9] EasyCopy User Manual"
.SH NAME
ec \- copy files and directories with ease
.SH SYNOPSIS
.SY ec
.I [options]
source target
.SY ec
.I [options]
source ... directory
.SY ec
.I [\-h | \-\-help]
.SY ec
.I [\-v | \-\-version]
.YS
.SH DESCRIPTION
Duplicate source to target.
.br
Copy source(s) into directory.
.br
Output the help.
.br
Output version information.
.SH OPTIONS
.SS Existing files
.TP
.I \-f, \-\-force
Overwrite existing files without asking.
.TP
.I \-i, \-\-interactive
Ask before overwriting a file.
.TP
.I \-n, \-\-no\-clobber
Skip existing files.

.SS User Interface
.TP
.I "   \-\-no\-config"
Do not read any user configuration files.
.TP
.I \-V \-\-verbose
Output more information.
.TP
.I "   \-\-color=WHEN"
Whether to colorize the output.
.I WHEN
can be any of
.RS
.TP
.I always
always put ANSII escape codes in the output, regardless of the context
.TP
.I auto
put ANSII escape codes in the output if the environment supports it:
.br
On Windows, colors are only enabled in Powershell.
.br
On Linux, colors are disabled, if stdout is a pipe.
.TP
.I never
never put ANSII escape codes in the output.
.RE
.TP
.I \-h \-\-help
Output the short help and exit.
.TP
.I \-v \-\-version
Output version information and exit.
.TP
.I "   \-\-copying"
Print conditions on redistributing EasyCopy source code.
.TP
.I "   \-\-warranty"
Print information on warranty provided with EasyCopy.
.SH EXIT STATUS
.TP
0
No problems have occured. Depending on the options, some files may have been overwritten or skipped without notice.
.TP
1
Minor problems have occured, e. g. a file was not readable, a device file was skipped or there was an error in the config file.
.TP
2
A major problem caused the program to abort it's task. More information can be found in the command output.
.SH EXAMPLES
.TP
.EX
.BI ec " foo/ bar"
.EE
Duplicate the folder
.I foo/
as
.IR bar/ .
.TP
.EX
.BI ec " /tmp/foo /mnt/bar ~/baz/"
.EE
Copy
.I /tmp/foo
and
.I /mnt/bar
to
.IR ~/baz/ .
.TP
.EX
.BI ec " -fV foo bar"
.EE
Duplicate
.I foo
as
.IR bar
while overwriting existing files and giving more information.
.SH FILES
.TP
.B ec.conf
The config file for EasyCopy in which the command-line flags can be set by default. For more information see
.BR ec.conf(5) .
.SH NOTES
If a file is skipped, it's content and attributes remain unchanged.
An exception to this is the
.B atime
which will be updated to the time it was visited (if supported by the system).
.SH REPORTING BUGS
Report bugs to the issue tracker of this project:
.UR https://github.com/scrouthtv/easy-copy/issues/
.UE
.SH COPYRIGHT
Copyright \[u00A9] 2020 The EasyCopy authors.
This software is licensed under GNU GPL v3.
For more information, read the LICENSE file that was distributed with this software.
.PP
Absolutely no warranty is provided for this software.
For more information read the LICENSE file that was distributed with this software or run the command
.IR "ec --warranty" .
.PP
This software uses third-party source code.
A copy of their LICENSE is distributed with EasyCopy.
.SH SEE ALSO
.B ec.conf(5)
.PP
For more information, visit the project's website via
.UR https://github.com/scrouthtv/easy-copy/
.UE .
